//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 10:44:49 PM MSK 
//


package com.epam.htsa.entity;


import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "event"
})
@XmlRootElement(name = "getEventResponse")
public class GetEventResponse {

    @XmlElement(required = true)
    protected Event event;

    /**
     * Gets the value of the event property.
     *
     * @return
     *     possible object is
     *     {@link Event }
     *
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     *
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

}
