//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 01:46:20 AM MSK 
//


package com.epam.htsa.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.htsa.soapclient.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.htsa.soapclient.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     *
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     *
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetEventResponse }
     *
     */
    public GetEventResponse createGetEventResponse() {
        return new GetEventResponse();
    }

    /**
     * Create an instance of {@link Event }
     *
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     *
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetAllEventRequest }
     *
     */
    public GetAllEventRequest createGetAllEventRequest() {
        return new GetAllEventRequest();
    }

    /**
     * Create an instance of {@link GetAllUserRequest }
     *
     */
    public GetAllUserRequest createGetAllUserRequest() {
        return new GetAllUserRequest();
    }

    /**
     * Create an instance of {@link GetAllUserResponse }
     *
     */
    public GetAllUserResponse createGetAllUserResponse() {
        return new GetAllUserResponse();
    }

    /**
     * Create an instance of {@link GetEventRequest }
     *
     */
    public GetEventRequest createGetEventRequest() {
        return new GetEventRequest();
    }

    /**
     * Create an instance of {@link GetAllEventResponse }
     *
     */
    public GetAllEventResponse createGetAllEventResponse() {
        return new GetAllEventResponse();
    }

    /**
     * Create an instance of {@link Auditorium }
     *
     */
    public Auditorium createAuditorium() {
        return new Auditorium();
    }

    /**
     * Create an instance of {@link Item }
     *
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Ticket }
     *
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link UserAccount }
     *
     */
    public UserAccount createUserAccount() {
        return new UserAccount();
    }

}
